<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <DevConfigsSkipDocumentationFile>true</DevConfigsSkipDocumentationFile>
        <EmbedAllSources>false</EmbedAllSources>
        <IncludeSymbols>false</IncludeSymbols>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    </PropertyGroup>
</Project>
